export default {
  bold: "Bold",
  bullets: "Bulleted list",
  code: "Preformatted text",
  heading1: "Heading T1",
  heading2: "Heading T2",
  heading3: "Heading T3",
  indent: "Indent",
  italic: "Italic",
  link: "Link",
  numbers: "Numbered list",
  outdent: "Outdent",
  quote: "Quoted text",
  redo: "Redo",
  remove: "Remove",
  small: "Small",
  strike: "Strikethrough",
  undo: "Undo",
  unlink: "Unlink",
  url: "URL",
  urlPlaceholder: "Enter a URL…",
}
